version: "3.8"

services:
  web:
    build: .
    container_name: wads-forum6
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_FIREBASE_API_KEY=${VITE_APP_FIREBASE_API_KEY}
      - VITE_APP_FIREBASE_AUTH_DOMAIN=${VITE_APP_FIREBASE_AUTH_DOMAIN}
      - VITE_APP_FIREBASE_PROJECT_ID=${VITE_APP_FIREBASE_PROJECT_ID}
      - VITE_APP_FIREBASE_STORAGE_BUCKET=${VITE_APP_FIREBASE_STORAGE_BUCKET}
      - VITE_APP_FIREBASE_MESSAGING_SENDER_ID=${VITE_APP_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_APP_FIREBASE_APP_ID=${VITE_APP_FIREBASE_APP_ID}
